# Generated by Django 5.1.2 on 2024-10-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contribution_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='api.story'),
        ),
    ]
