# Generated by Django 5.1.2 on 2024-10-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contribution_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='created_at',
            new_name='contributed_at',
        ),
    ]
