# Generated by Django 5.1.2 on 2024-10-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_created_at_contribution_contributed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='content',
            field=models.TextField(default='This is an amazing story!'),
            preserve_default=False,
        ),
    ]
